apiVersion: req.nephio.org/v1alpha1
kind: Interface
metadata: # kpt-merge: /n4
  name: n4
  annotations:
    config.kubernetes.io/local-config: "true"
    internal.kpt.dev/upstream-identifier: 'req.nephio.org|Interface|default|n4'
spec:
  networkInstance:
    name: vpc-internal
  cniType: sriov
  attachmentType: vlan
